USE ControleDeVendas

CREATE TABLE Cliente(
  CLI_ID INT IDENTITY(1, 1) PRIMARY KEY,
  CLI_NOMERAZAO VARCHAR(80),
  CLI_CNPJCPF VARCHAR(20),
  CLI_LOGRADOURO VARCHAR(80),
  CLI_BAIRRO VARCHAR(50),
  CLI_CIDADE VARCHAR(50),
  CLI_UF VARCHAR(2),
  CLI_CEP VARCHAR(8),
  CLI_EMAIL VARCHAR(80),
  CLI_FONES VARCHAR(50),
  CLI_DATACADASTRO DATETIME
)

CREATE TABLE Pedido(
  PED_ID INT IDENTITY(1, 1) PRIMARY KEY,
  CLI_ID INT FOREIGN KEY REFERENCES Cliente(CLI_ID),
  PED_DATAENCOMENDA DATETIME,
  PED_VALOR MONEY, 
  PED_STATUS VARCHAR(1)
)


CREATE TABLE Categoria(
  CAT_ID INT IDENTITY(1, 1) PRIMARY KEY,
  CAT_DESCRICAO VARCHAR(50)
)

CREATE TABLE Produto(
  PRO_ID INT IDENTITY(1, 1) PRIMARY KEY, 
  CAT_ID INT FOREIGN KEY REFERENCES Categoria(CAT_ID),
  PRO_DESCRICAO VARCHAR(50),
  PRO_QTDESTOQUE INT,
  PRO_VALOR MONEY, 
  PRO_ATIVO BIT default 'FALSE'
)

CREATE TABLE Item(
  ITE_ID INT IDENTITY(1, 1) PRIMARY KEY, 
  PED_ID INT FOREIGN KEY REFERENCES Pedido(PED_ID),
  PRO_ID INT FOREIGN KEY REFERENCES Produto(PRO_ID),
  ITE_QTDE INT,
  ITE_VALOR MONEY
)